### ISSUE TITLE
Websocket ECONNRESET

### ISSUE THREAD

**Issue by mikbry** [Zoapp/backend#1]
**Context**
node version: v8.5.0
zoapp-backend version: 0.8.3
environment: yarn start:dev on MacOS

**What are you trying to achieve or the steps to reproduce ?**
On Browser reload FrontEnd, or in test close socket abruptly.
The backend socket client should close silently with a log:
```
2018-01-07T12:32:33.173Z - info: Error caught:
2018-01-07T12:32:33.185Z - info: Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
```
In ./websocket/index.js line 136 Socket error are handled to close the client.

**Which result you had ?**
Time to time the socket client crash the server. We have this log:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
[nodemon] app crashed - waiting for file changes before starting...
```
Same ECONNRESET is not catched by line 136.
No previous error catched. The previous log sometime look like this:
```
(node:20321) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'id' of null
(node:20321) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
intents version= undefined
2018-01-06T20:24:10.361Z - info: tunnel.active= provider=localtunnel, port=8081, subdomain=hnefnrzibv 
```
But it doesn't seems to be related.

**TODO**
Isolate more precisely the bug and create a test case. In general create test cases for Websocket.

**Comment by mikbry** [comment]
Another option is that this crash isn't related to websocket, but linked to Express...

**Comment by mikbry** [comment]
The bug is always present
